package-lock.json
package.json
src/routes/LabelExPage.jsx

react-canvas-draw 의존성 문제로 인해 수동으로 패키지 뜯어냈습니다

Fix : react-canvas-draw revert

---

.eslintrc.json
.gitignore
.husky/pre-commit
.husky/pre-push
.prettierrc
package-lock.json
package.json
public/index.html
src/App.test.js
src/index.js
src/reportWebVitals.js
src/routes/LabelExPage.jsx
src/setupTests.js

- eslint, prettier를 적용했습니다.
- 위 사항이 커밋 시에 자동으로 적용되도록 husky와 lint-staged를 사용했습니다.
> commit 전에 prettier formatting이 잘 적용 되어있는지 검사
> push 전에 eslint 규칙이 적용 되었는지 검사
- 아래 가이드와 husky docs를 참고했습니다.
> https://jihyundev.tistory.com/25
- husky는 최근 버전 업데이트로 인해서 구글의 모든 블로그가 잘못된 정보를 가르쳐주므로, 공식 docs를 참고해야합니다.

feat: eslint, prettier, husky, lint-staged 세팅

---

src/routes/LabelExPage.jsx

그림 그리는 기능 추가 (도형 추가, 텍스트 추가 등 기능은 없음. 지우개 기능 없음.)

Feat: basic drawing

---

.eslintrc.json
src/App.js
src/components/Banner/index.jsx
src/components/Header/index.jsx
src/mappingData/Carelabel-info.json
src/routes/LabelSearchPage.jsx

label search page 기본 구조 구현
mappingData에 오타 하나 수정
Header의 height, width가 간헐적으로 0으로 잡히던 오류 수정
button이 button을 포함하던 오류 수정
코딩 난이도를 999999배 올리던 eslint unused variable 속성 변경
원래는 커밋 나눠서 올려야하지만 졸려서 그냥 한번에 올릴게요

feat: LabelSearchPage 구현

---

.github/workflows/lint-check.yml

병합 시에 lint check를 자동화해주는 workflow를 구축했습니다.
자동 배포랑 한 파일로 구축해도 될거 같긴 한데, 일단 해보고 동작 하면 합쳐보겠습니다

lint check workflow 구축

---

.github/workflows/deploy.yml

자동 배포 되도록 workflow 파일을 구축했습니다
거의 복붙해서 될지 안될지는 잘 모름
일단 올리고 되나 볼게요(merge 해야 테스트 가능하기에 선 pr 어쩔 수 없음)
lint check는 다른 워크플로우에 구축해서 여기 없슴다

Feat: CD workflow 구축

---

src/routes/CareSearchPage.jsx

test commit

---

.github/workflows/deploy.yml
src/components/Header/index.jsx

이상한거 넣은거 없앰

---

src/components/Banner/index.jsx
src/components/Footer/index.jsx
src/components/Header/index.jsx
src/components/LabelCard/index.jsx
src/routes/LabelSearchPage.jsx

refactor: div지옥 없애기

---

src/App.js
src/components/LabelCard/index.jsx
src/mappingData/Carelabel-info.json
src/routes/LabelSearchPage.jsx

.map( (?) => <component>) 구조에서 key를 지정하지 않아 생기는 warning 해결

resolve: key warning

---

.github/workflows/deploy.yml

action이 잘 동작하지 않아서 수정본을 테스트 합니다

캐시 무효화 테스트

---

.github/workflows/deploy.yml

CDN cache test(3)

---

.github/workflows/deploy.yml

CDN cache test(4)

---

.github/workflows/deploy.yml

s3 업로드를 위해서 환경변수를 github action으로 생성해주는 코드 추가
아직 정확히 동작하는지는 몰라요(테스트 예정)

Feat : s3 업로드를 위한 env 파일 생성

---

src/components/Canvas/canvasinput.js
src/components/Canvas/index.jsx

캔버스 전체 지우기 기능이 작동 안돼서 수정
캔버스 작동 방식이 기존과 달라짐에 따라 clearRect 함수를 사용할 수 없게 되어, history 전체를 비우는 방식으로 변경했습니다

Feat: canvas refresh function edited

---

src/components/Banner/index.jsx
src/components/Dropdown/index.jsx
src/components/Footer/index.jsx
src/components/Header/index.jsx
src/components/LabelCard/index.jsx
src/index.css
src/routes/CareSearchPage.jsx
src/routes/LabelExPage.jsx
src/routes/LabelSearchPage.jsx

tailwind 지옥을 드디어! index.css로 이전시켰습니다... (다는 아님)
실수한 부분이 있을까 걱정이 되네요
이 커밋이 적용되었을 때 디자인이 달라지진 않는지 확인해주시면 좋을 것 같아요.

refactor: tailwind 지옥을 index.css로 이전

---

src/routes/CareResultPage.jsx
src/routes/CareSearchPage.jsx

서술형 result 페이지는.... 인공지능쪽 되는지 여부를 보고...
코드가 매우 더러워용(경악 금지)

feat: care search 서술형 문형 구현 + 디테일 수정

---

src/components/Dropdown/index.jsx
src/routes/CareSearchPage.jsx

resolve dependency warning & missing alt warning

---

src/routes/CareSearchPage.jsx

지원이가 싫어하는 default 라디오버튼을 드디어 커스텀했어요

---

.github/workflows/deploy.yml
package-lock.json
package.json
src/chatgpt.js

인코딩된 이미지 문자열을 입력으로 넣으면 결과를 list로 뽑아주는 api 함수 구현

Feat: gpt 라벨 검색 api

---

src/chatgpt.js
src/components/Canvas/index.jsx
src/components/Modal/index.jsx
src/routes/LabelExPage.jsx
src/routes/LabelExResultPage.jsx

`src/routes/LabelExPage.jsx
`
1. 이미지 업로드해서 base64 인코딩 후 gpt api 호출
2. state 변수인 isLoading이 true로 바뀌며 로딩창 띄워짐
3. api 응답 받아와서 useNavigate의 state로 넣음. 
`src/components/Canvas/index.jsx
`
1. 그림을 blob 객체로 변환 후 base64 인코딩 후 gpt api 호출
나머지는 위와 동일

Feat: image search api done
